[project]
name = "arista-ztp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ansible>=10.7.0",
    "ansible-core>=2.17.14",
    "requests>=2.32.5",
]
